# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedproducts',
            name='productImage',
            field=models.ImageField(upload_to=b''),
        ),
    ]
