# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-30 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('useraddress', models.CharField(max_length=3000)),
                ('userpassword', models.CharField(max_length=100)),
                ('userphonenumber', models.IntegerField(default=0)),
            ],
        ),
    ]
