# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-30 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginOrSignupSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userphonenumber',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
