# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-30 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginOrSignupSystem', '0002_auto_20201030_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userphonenumber',
            field=models.IntegerField(default=0),
        ),
    ]
